#IMPORTAMOS EL DOCUMENTO QUE QUEREMOS USAR
#INDICAMOS QUE UTILICE TODAS LAS FUNCIONES DEFINIDAS 
from funciones_matematicas import *
sumar(20,45)
restar(34, 2)


#import funciones_matematicas => from funciones_matematicas import * 
#LA DIFERENCIA ES QUE EL PRIMERO TIENES QUE INDICAR UNA A UNA LAS FUNCIONES MIENTARS QUE EN EL SEGUNDO, LAS IMPORTA DE GOLPE